import { BrowserMultiFormatReader } from "https://cdn.jsdelivr.net/npm/@zxing/browser@0.1.5/+esm";
const $=id=>document.getElementById(id);const todayKey=()=> "caltracksz-log-"+new Date().toISOString().slice(0,10);
let goal=Number(localStorage.getItem("goal")||2200),items=JSON.parse(localStorage.getItem(todayKey())||"[]"),scannerControls=null,deferredPrompt=null;
function save(){localStorage.setItem(todayKey(),JSON.stringify(items))}
function addItem(item){const kcal=Math.round(Number(item.kcal));if(!item.name||!kcal||kcal<=0)return;items.push({name:item.name,kcal,protein:item.protein??null,source:item.source??"handmatig",time:new Date().toLocaleTimeString("nl-NL",{hour:"2-digit",minute:"2-digit"})});save();render()}
function render(){const total=items.reduce((s,x)=>s+x.kcal,0),left=Math.max(goal-total,0),pct=Math.min(total/goal*100,100);$("totalText").textContent=total;$("leftText").textContent=left;$("goalText").textContent=goal;$("progressBar").style.width=pct+"%";$("log").innerHTML="";$("emptyLog").style.display=items.length?"none":"block";for(const[i,item]of items.entries()){const li=document.createElement("li");li.innerHTML=`<span><strong>${item.name}</strong><br><small>${item.source} • ${item.time}</small></span><b>${item.kcal} kcal</b>`;const btn=document.createElement("button");btn.className="remove";btn.textContent="×";btn.onclick=()=>{items.splice(i,1);save();render()};li.appendChild(btn);$("log").appendChild(li)}}
document.querySelectorAll(".tab").forEach(btn=>{btn.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".panel").forEach(x=>x.classList.remove("active"));btn.classList.add("active");$(btn.dataset.tab).classList.add("active")}});
$("mealPhoto").onchange=e=>{const file=e.target.files[0];if(!file)return;$("photoPreview").src=URL.createObjectURL(file);$("photoPreview").hidden=false};
$("analyzeMeal").onclick=async()=>{const file=$("mealPhoto").files[0],text=$("mealText").value.trim();$("aiOutput").innerHTML=`<div class="result">Maaltijd analyseren...</div>`;try{const formData=new FormData();if(file)formData.append("photo",file);formData.append("text",text);const response=await fetch("http://localhost:3000/api/analyze-meal",{method:"POST",body:formData});if(!response.ok)throw new Error("Backend niet bereikbaar.");showAIResult(await response.json())}catch(err){const fallback=offlineMealEstimate(text);showAIResult({meal:fallback.meal,calories:fallback.calories,protein:fallback.protein,confidence:"offline schatting",note:"Echte foto-AI werkt zodra je backend online staat en gekoppeld is."})}};
function offlineMealEstimate(text){const t=text.toLowerCase();let calories=600,protein=25,meal=text||"Maaltijd van foto";if(t.includes("pizza"))calories=850;if(t.includes("kip")&&t.includes("rijst")){calories=650;protein=45}if(t.includes("pasta"))calories=700;if(t.includes("kapsalon"))calories=1200;if(t.includes("salade"))calories=350;return{meal,calories,protein}}
function showAIResult(data){$("aiOutput").innerHTML=`<div class="result"><p>Maaltijd: <strong>${data.meal||"Onbekend"}</strong></p><p>Calorieën: <strong>${data.calories||0} kcal</strong></p><p>Eiwit: ${data.protein||"?"} g</p><p class="muted">Zekerheid: ${data.confidence||"onbekend"}</p>${data.note?`<p class="muted">${data.note}</p>`:""}<button id="addAI" class="primary full">Toevoegen aan logboek</button></div>`;$("addAI").onclick=()=>addItem({name:data.meal||"AI maaltijd",kcal:data.calories||0,protein:data.protein,source:"AI"})}
async function lookupBarcode(code){$("barcodeOutput").innerHTML=`<div class="result">Product zoeken...</div>`;const res=await fetch(`https://world.openfoodfacts.org/api/v0/product/${encodeURIComponent(code)}.json`),data=await res.json();if(!data.product){$("barcodeOutput").innerHTML=`<div class="result">Product niet gevonden. Voeg het handmatig toe.</div>`;return}const p=data.product,name=p.product_name||p.brands||"Onbekend product",kcal100=p.nutriments?.["energy-kcal_100g"]||(p.nutriments?.["energy_100g"]?Math.round(p.nutriments["energy_100g"]/4.184):null);if(!kcal100){$("barcodeOutput").innerHTML=`<div class="result">${name} gevonden, maar calorieën ontbreken.</div>`;return}$("barcodeOutput").innerHTML=`<div class="result"><p>Product: <strong>${name}</strong></p><p><strong>${Math.round(kcal100)} kcal</strong> per 100g</p><input id="grams" type="number" value="100" placeholder="Aantal gram"><button id="addBarcode" class="primary full">Toevoegen</button></div>`;$("addBarcode").onclick=()=>{const grams=Number($("grams").value||100);addItem({name:`${name} (${grams}g)`,kcal:kcal100*grams/100,source:"barcode"})}}
$("lookupBarcode").onclick=()=>{const code=$("barcodeInput").value.trim();if(code)lookupBarcode(code)};
$("startScan").onclick=async()=>{const reader=new BrowserMultiFormatReader();$("barcodeOutput").innerHTML=`<div class="result">Richt je camera op de barcode...</div>`;scannerControls=await reader.decodeFromVideoDevice(undefined,"video",(result,error,controls)=>{if(result){const code=result.getText();$("barcodeInput").value=code;controls.stop();lookupBarcode(code)}})};
$("stopScan").onclick=()=>{if(scannerControls)scannerControls.stop()};
$("addManual").onclick=()=>{addItem({name:$("manualName").value.trim(),kcal:Number($("manualKcal").value),source:"handmatig"});$("manualName").value="";$("manualKcal").value=""};
$("saveGoal").onclick=()=>{const newGoal=Number($("goalInput").value);if(newGoal>0){goal=newGoal;localStorage.setItem("goal",goal);render()}};
$("clearDay").onclick=()=>{items=[];save();render()};
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("installBtn").hidden=false});
$("installBtn").onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();deferredPrompt=null;$("installBtn").hidden=true};
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js");
render();
